### PR TITLE
Fix WT library build

### PR DESCRIPTION
**Pull request by mccullocht**
The published version of this library fails to build out of the box when it attempts to remove the `third_party` directory.
Move the library download into `OUT_DIR`, which also fixes issues where `cargo test` would fail to link while searching
for a `dylib` version of the library on macos.

Fix `cargo clippy` issues and rustfmt the code.

### CODE REVIEW

**Comment by mpobrien** [comment]
@mccullocht apologies for not seeing this PR earlier!
We made a few fixes already which might address some of what you mentioned, but not all. Would you mind rebasing on the latest in `main` and then we can get this merged in?

**Comment by mccullocht** [comment]
@mpobrien rebased and at this point it's just clippy lint fixes so might not be worth merging. I previously had issues writing tests but that seems to be resolved (maybe due to the separate crate?).

**Comment by mpobrien** [comment]
I think we will need to get clippy and GHA going on this repo so that it will prevent the lint issues from creeping in in the first place, but couldn't hurt to merge these for now anyway!

**Comment by mccullocht** [comment]
IIRC clicking on the 'actions' tab should help you write a file that does cargo build/test/clippy, or you can copy the config from a repo of mine (https://github.com/mccullocht/easy_tiger/blob/main/.github/workflows/rust.yml)

**Pull request merged**
